### PR TITLE
[STRUCTURE] Update project structure to better Developer Experience

### PR DESCRIPTION
**Pull request by racerxdl**

### CODE REVIEW

**Comment by racerxdl** [comment]
> Nice!!!
> 
> I have just a few questions:
> 
> * Could the /wrappers folders stay inside the /pkg folder? (because its something to be shared)
Technically the pkg is for sharing go code, the go code inside the wrappers are just `unsafe low level` conversions for being able to call it from a native library. I'm not sure if its a good thing to put inside `pkg`. @rdleal what do you think?

> * /testdata folder I think is called just /test (maybe with a data folder inside?)
A `test` folder doesn't make much sense in golang because the tests are usually in the same folder as the tested stuff. This testdata folder are for assets needed for testing file loads and stuff like that.
> * /logo folder I think would go inside an /assets folder
Moved logo folder inside /assets! That makes sense.

**Comment by rdleal** [comment]
quote @racerxdl 

> Technically the pkg is for sharing go code, the go code inside the wrappers are just unsafe low level conversions for being able to call it from a native library. I'm not sure if its a good thing to put inside pkg. @rdleal what do you think?

The directory `wrappers` seems a bit odd in the middle of the repository. I would suggest put it inside a `tools` directory, as its contents seem to be more like a tooling for generating dynamic libraries and nodejs native libraries, like the [istio tools directory](https://github.com/istio/istio/tree/master/tools) has code to generate packages (rpm, deb, etc...).

**Comment by toyoaki** [comment]
> Quote @toyoaki
> 
> > Nice!!!
> > I have just a few questions:
> > 
> > * Could the /wrappers folders stay inside the /pkg folder? (because its something to be shared)
> 
> Technically the pkg is for sharing go code, the go code inside the wrappers are just `unsafe low level` conversions for being able to call it from a native library. I'm not sure if its a good thing to put inside `pkg`. @rdleal what do you think?
> 
Got it, then I agree with you it shouldn't be in in the /pkg folder.
> > * /testdata folder I think is called just /test (maybe with a data folder inside?)
> 
> A `test` folder doesn't make much sense in golang because the tests are usually in the same folder as the tested stuff. This testdata folder are for assets needed for testing file loads and stuff like that.
> 
I got the suggestion from https://github.com/golang-standards/project-layout/tree/master/test. But if it still doesn't make sense ok!
> > * /logo folder I think would go inside an /assets folder
> 
> Moved logo folder inside /assets! That makes sense.

**Comment by rdleal** [comment]
@toyoaki indeed following the convention the folder `testdata` should be renamed to `test` and the files inside the `testdata` that aren't `.go` files, should be moved to the `test/testdata`.

**Comment by racerxdl** [comment]
Done @rdleal / @toyoaki !

**Pull request merged**
